export default [{
  title: 'Dashboard',
  icon: 'gauge',
  path: '/dashboard',
}, {
  title: 'Task',
  icon: 'calendar-check',
  path: '/task',
}, {
  title: 'Project',
  icon: 'layer-group',
  path: '/project'
}, {
  title: 'Product',
  icon: 'atom',
  path: '/product'
}, {
  title: 'Data',
  icon: 'database',
  path: '/data'
}, {
  title: 'Website',
  icon: 'globe',
  path: '/website'
}, {
  title: 'Blog',
  icon: 'blog',
  path: '/blog'
}, {
  title: 'Sectum',
  icon: 'sectum',
  path: '/sectum/'
}]