export interface PartTable {
  PartId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Unit?: string,
  Detail?: string,
  Mass?: number,
  Material?: string,
  Surface?: string,
  Standard?: string,
  Symbol?: string,
}

export interface PartDetail {
  PartId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Unit?: string,
  Detail?: string,
  Mass?: string,
  Material?: string,
  Surface?: string,
  Standard?: string,
  Symbol?: string,
  Select: SelectList[],
  File: FileList[],
  DesignBy?: string,
  DesignAt?: string,
  DraftBy?: string,
  DraftAt?: string,
  InspectBy?: string,
  InspectAt?: string,
  DirectBy?: string,
  DirectAt?: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}

export interface SelectList {
  BrandId: number,
  Brand: string,
  Purchase: PurchaseList[]
}
export interface PurchaseList {
  Model: string,
  Cost: number,
  Price: number,
}
export interface AppendixList {
  AppendixId?: number,
  DataId: number,
  StorageId: number
}
export interface AppendixDelete {
  AppendixId: number
}
export interface FileList {
  Name: string,
  Type: string,
  Link: string,
}
export interface SectionTable {
  SectionId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Detail?: string,
}
export interface SectionDetail {
  SectionId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Detail?: string,
  Select: SelectList[],
  File: FileList[],
  DesignBy?: string,
  DesignAt?: string,
  DraftBy?: string,
  DraftAt?: string,
  InspectBy?: string,
  InspectAt?: string,
  DirectBy?: string,
  DirectAt?: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}
export interface SectionPartTable {
  PartId: number,
  Name: string,
  Model: string,
  Mass: number,
  Quantity: number,
  Reference: string,
}
export interface SourceTable {
  SectionId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Detail?: string,
}
export interface SourceDetail {
  SourceId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Detail?: string,
  File: FileList[],
  DesignBy?: string,
  DesignAt?: string,
  DraftBy?: string,
  DraftAt?: string,
  InspectBy?: string,
  InspectAt?: string,
  DirectBy?: string,
  DirectAt?: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}
export interface StandardTable {
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Point: number,
  Detail?: string,
  Desity: string,
  Yield: string,
  Ultima: string,
  Elastic: string,
}
export interface StandardDetail {
  StandardId: number,
  Code: number,
  Ver: number,
  Name: string,
  Model: string,
  Point: number,
  Detail?: string,
  Desity: string,
  Yield: string,
  Ultima: string,
  Elastic: string,
  File: FileList[],
  DesignBy?: string,
  DesignAt?: string,
  DraftBy?: string,
  DraftAt?: string,
  InspectBy?: string,
  InspectAt?: string,
  DirectBy?: string,
  DirectAt?: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}
export interface ProjectTable {
  Code: number,
  Ver: number,
  Name: string,
  Purpose: string,
  Target: string,
}
export interface ProjectDetail {
  ProjectId: number,
  Code: number,
  Ver: number,
  Name: string,
  Purpose: string,
  Target: string,
  CreateBy?: string,
  CreateAt?: string,
  InspectBy?: string,
  InspectAt?: string,
  DirectBy?: string,
  DirectAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}
export interface TaskTable {
  TaskId: number,
  Title: string,
  IsCompleted: boolean,
  Sponsor: string,
  Executor: string,
  Profile: string,
  StartAt: string,
  EndAt: string,
}
export interface TaskDetail {
  TaskId: number,
  Title: string,
  IsCompleted: boolean,
  Sponsor: string,
  Executor: string,
  Profile: string,
  StartAt: string,
  EndAt: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}
export interface StorageTable {
  StorageId: number,
  Name: string,
  Size: number,
  Type: string,
  Bucket: string,
  Link: string,
}
export interface StorageDetail {
  StorageId: number,
  Name: string,
  Size: number,
  Type: string,
  Bucket: string,
  Link: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}
export interface InterlinkTable {
  Code: number,
  Ver: number,
  Name: string,
  Contact: string,
  Phone: string,
  Gender: string,
  Birthday: string,
  Detail: string
  Address: string,
  Website: string,
}
export interface InterlinkDetail {
  InterlinkId: number,
  Code: number,
  Ver: number,
  Name: string,
  Contact: string,
  Phone: string,
  Gender: string,
  Birthday: string,
  Detail: string,
  Address: string,
  Website: string,
  CreateBy?: string,
  CreateAt?: string,
  UpdateBy?: string,
  UndateAt?: string,
  DeleteBy?: string,
  DeleteAt?: string,
  Remark?: string,
}

